# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "ccb34be02e32f39aa7574d6b5fda95f01ea9eb0d"

[[deps.BaseDirs]]
git-tree-sha1 = "bca794632b8a9bbe159d56bf9e31c422671b35e0"
uuid = "18cc8868-cbac-4acf-b575-c8ff214dc66f"
version = "1.3.2"

[[deps.SimpleBLE]]
path = "."
uuid = "c43e3543-e659-46d0-a341-79c7b8740d4a"
version = "0.2.1"
