name = "SimpleBLE"
uuid = "c43e3543-e659-46d0-a341-79c7b8740d4a"
version = "0.3.4"
authors = ["Awesome Quest <torfit@gmail.com>"]

[workspace]
projects = ["docs", "test"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SimpleBLE_jll = "65d2f289-9923-54e7-9bd2-c5e9669d2a86"

[compat]
Libdl = "1.11.0"
SimpleBLE_jll = "0.12.1"
